const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
try { require('dotenv').config(); } catch {}
function loadEnv(){try{const fs=require('fs'),path=require('path');const f=path.join(__dirname,'.env');if(!fs.existsSync(f))return;for(const line of fs.readFileSync(f,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'');}}catch{}}
loadEnv();
const {db, verifyPassword, scryptHash, iso} = require('./db');

const PORT = Number(process.env.PORT || 3000);
const JWT_SECRET = process.env.JWT_SECRET || 'change-this-secret-before-production';
const ROOT = __dirname;
const PUBLIC = path.join(ROOT,'public');
const UPLOADS = path.join(PUBLIC,'uploads');
fs.mkdirSync(UPLOADS,{recursive:true});
const TOKEN_TTL = 7*24*60*60;

function b64url(s){return Buffer.from(s).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
function signToken(payload){const header=b64url(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=b64url(JSON.stringify(Object.assign({},payload,{iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+TOKEN_TTL})));const sig=b64url(crypto.createHmac('sha256',JWT_SECRET).update(header+'.'+body).digest());return header+'.'+body+'.'+sig;}
function verifyToken(token){try{const [h,p,s]=String(token||'').split('.');if(!h||!p||!s)return null;const expected=b64url(crypto.createHmac('sha256',JWT_SECRET).update(h+'.'+p).digest());if(expected!==s)return null;const payload=JSON.parse(Buffer.from(p,'base64url').toString('utf8'));if(payload.exp && payload.exp<Math.floor(Date.now()/1000))return null;return payload;}catch{return null;}}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','X-Content-Type-Options':'nosniff'});res.end(body);}
function error(res,status,msg){json(res,status,{error:msg});}
function publicUser(u){return {id:u.id,name:u.name,email:u.email,role:u.role,phone:u.phone||'',createdAt:u.created_at};}
function auth(req,res,optional=false){const header=req.headers.authorization||'';const t=header.startsWith('Bearer ')?header.slice(7):'';const p=verifyToken(t);if(!p&&!optional){error(res,401,'Authentication required');return null;}return p;}
function requireAdmin(req,res){const p=auth(req,res);if(!p)return null;if(p.role!=='admin'){error(res,403,'Admin access required');return null;}return p;}
function orderItems(id){return db.prepare('SELECT product_id AS id,product_name AS name,quantity,price FROM order_items WHERE order_id=?').all(id);}
function safeNum(v){return Number.isFinite(Number(v))?Number(v):0;}

function productVariants(productId, activeOnly=true){
  const q = activeOnly
    ? 'SELECT id,product_id AS productId,name,sku,price,old_price AS oldPrice,stock,active FROM product_variants WHERE product_id=? AND active=1 ORDER BY id'
    : 'SELECT id,product_id AS productId,name,sku,price,old_price AS oldPrice,stock,active FROM product_variants WHERE product_id=? ORDER BY id';
  return db.prepare(q).all(productId);
}
function publicProducts(activeOnly=true){
  const q = activeOnly
    ? 'SELECT id,name,brand,category,price,old_price AS oldPrice,storage,color,badge,description,stock,rating,review_count AS reviewCount,image,active FROM products WHERE active=1 ORDER BY id'
    : 'SELECT id,name,brand,category,price,old_price AS oldPrice,storage,color,badge,description,stock,rating,review_count AS reviewCount,image,active FROM products ORDER BY id DESC';
  return db.prepare(q).all().map(p=>Object.assign(p,{variants:productVariants(p.id,activeOnly)}));
}
function promoRow(code){
  const c=String(code||'').trim().toUpperCase();
  return db.prepare('SELECT id,code,type,value,max_uses AS maxUses,uses_count AS usesCount,expires_at AS expiresAt,active FROM promo_codes WHERE code=?').get(c);
}
function calculatePromo(row, subtotal){
  if(!row || !row.active) return 0;
  if(row.expiresAt && new Date(row.expiresAt).getTime() < Date.now()) return 0;
  if(row.maxUses>0 && row.usesCount>=row.maxUses) return 0;
  if(row.type==='fixed') return Math.min(Number(row.value)||0, subtotal);
  return Math.min(subtotal, Math.round(subtotal * ((Number(row.value)||0)/100)));
}
function touchUserNotification(userId,title,body){ if(userId) db.prepare('INSERT INTO notifications(user_id,title,body,created_at) VALUES(?,?,?,?)').run(userId,title,body,iso()); }

function uid(prefix){return prefix+Math.floor(100000+Math.random()*900000);}
function parseJson(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>12_000_000)req.destroy();});req.on('end',()=>{if(!raw)return resolve({});try{resolve(JSON.parse(raw))}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject);});}
function setSecurity(res,contentType){res.setHeader('Content-Type',contentType);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');}
function fileResponse(req,res,pathname){const safe=pathname==='/'?'/index.html':pathname;const full=path.normalize(path.join(PUBLIC,safe));if(!full.startsWith(PUBLIC))return error(res,403,'Forbidden');const ext=path.extname(full);fs.readFile(full,(err,data)=>{if(err){if(ext)return error(res,404,'Not found');return fs.readFile(path.join(PUBLIC,'index.html'),(e,d)=>{if(e)return error(res,404,'Not found');setSecurity(res,'text/html; charset=utf-8');res.end(d);});}const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};setSecurity(res,types[ext]||'application/octet-stream');if(ext==='.html')res.setHeader('Cache-Control','no-store');res.end(data);});}

async function api(req,res,url){
  const {pathname,searchParams}=url; const method=req.method;
  if(method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'});return res.end();}
  let body={}; if(['POST','PUT','PATCH'].includes(method)){try{body=await parseJson(req);}catch{return error(res,400,'Invalid JSON');}}
  if(pathname==='/health'&&method==='GET')return json(res,200,{ok:true,service:'NEXORA',time:iso()});
  if(pathname==='/api/health'&&method==='GET')return json(res,200,{ok:true,service:'NEXORA API',time:iso()});
  if(pathname==='/api/auth/register'&&method==='POST'){const name=String(body.name||'').trim(),email=String(body.email||'').trim().toLowerCase(),password=String(body.password||'');if(!name||!email||password.length<6)return error(res,400,'Name, email and password (6+ chars) are required');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return error(res,409,'An account with this email already exists');const now=iso();const info=db.prepare("INSERT INTO users(name,email,password_hash,role,phone,created_at,updated_at) VALUES (?,?,?,'customer',?,?,?)").run(name,email,scryptHash(password),String(body.phone||''),now,now);const u=db.prepare('SELECT * FROM users WHERE id=?').get(Number(info.lastInsertRowid));return json(res,201,{token:signToken({sub:u.id,role:u.role,email:u.email,name:u.name}),user:publicUser(u)});}
  if(pathname==='/api/auth/login'&&method==='POST'){const email=String(body.email||'').trim().toLowerCase();const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!verifyPassword(body.password,u.password_hash))return error(res,401,'Email or password is incorrect');return json(res,200,{token:signToken({sub:u.id,role:u.role,email:u.email,name:u.name}),user:publicUser(u)});}
  if(pathname==='/api/me'&&method==='GET'){const p=auth(req,res);if(!p)return;const u=db.prepare('SELECT * FROM users WHERE id=?').get(p.sub);if(!u)return error(res,404,'User not found');return json(res,200,{user:publicUser(u)});}
  if(pathname==='/api/me'&&method==='PUT'){const p=auth(req,res);if(!p)return;const u=db.prepare('SELECT * FROM users WHERE id=?').get(p.sub);if(!u)return error(res,404,'User not found');const name=String(body.name??u.name).trim(),email=String(body.email??u.email).trim().toLowerCase();if(!name||!email)return error(res,400,'Name and email are required');if(db.prepare('SELECT id FROM users WHERE email=? AND id<>?').get(email,u.id))return error(res,409,'Email is already in use');const phone=String(body.phone??u.phone??'').trim();db.prepare('UPDATE users SET name=?,email=?,phone=?,updated_at=? WHERE id=?').run(name,email,phone,iso(),u.id);const n=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);return json(res,200,{token:signToken({sub:n.id,role:n.role,email:n.email,name:n.name}),user:publicUser(n)});}
  if(pathname==='/api/products'&&method==='GET'){return json(res,200,{products:publicProducts(true)});}
  const reviewMatch=pathname.match(/^\/api\/products\/(\d+)\/reviews$/);if(reviewMatch){const pid=Number(reviewMatch[1]);if(method==='GET'){const reviews=db.prepare("SELECT r.id,r.rating,r.text,r.created_at AS date,u.name FROM reviews r LEFT JOIN users u ON u.id=r.user_id WHERE r.product_id=? ORDER BY r.id DESC").all(pid);const agg=db.prepare('SELECT ROUND(COALESCE(AVG(rating),4.8),1) AS avg,COUNT(*) AS count FROM reviews WHERE product_id=?').get(pid);return json(res,200,{reviews,rating:{avg:Number(agg.avg),count:Number(agg.count)}});}if(method==='POST'){const p=auth(req,res);if(!p)return;const text=String(body.text||'').trim(),rating=Number(body.rating);if(!text||!Number.isInteger(rating)||rating<1||rating>5)return error(res,400,'Valid rating and text are required');if(!db.prepare('SELECT id FROM products WHERE id=? AND active=1').get(pid))return error(res,404,'Product not found');db.prepare('INSERT INTO reviews(product_id,user_id,rating,text,created_at) VALUES (?,?,?,?,?)').run(pid,p.sub,rating,text,iso());const agg=db.prepare('SELECT ROUND(AVG(rating),1) AS avg,COUNT(*) AS count FROM reviews WHERE product_id=?').get(pid);db.prepare('UPDATE products SET rating=?,review_count=?,updated_at=? WHERE id=?').run(Number(agg.avg),Number(agg.count),iso(),pid);return json(res,201,{ok:true,rating:{avg:Number(agg.avg),count:Number(agg.count)}});}}
  if(pathname==='/api/me/favorites'&&method==='GET'){const p=auth(req,res);if(!p)return;return json(res,200,{favorites:db.prepare('SELECT product_id AS id FROM favorites WHERE user_id=? ORDER BY created_at DESC').all(p.sub).map(x=>x.id)});}
  const favMatch=pathname.match(/^\/api\/me\/favorites\/(\d+)$/);if(favMatch){const p=auth(req,res);if(!p)return;const id=Number(favMatch[1]);if(method==='POST')db.prepare('INSERT OR IGNORE INTO favorites(user_id,product_id,created_at) VALUES (?,?,?)').run(p.sub,id,iso());else if(method==='DELETE')db.prepare('DELETE FROM favorites WHERE user_id=? AND product_id=?').run(p.sub,id);else return error(res,405,'Method not allowed');return json(res,200,{ok:true});}
  if(pathname==='/api/orders'&&method==='GET'){const p=auth(req,res);if(!p)return;const orders=db.prepare('SELECT id,customer_name AS name,email,phone,city,address,delivery,payment,note,subtotal,discount,delivery_fee AS deliveryFee,total,status,progress,created_at AS date,updated_at AS updatedAt FROM orders WHERE user_id=? ORDER BY created_at DESC').all(p.sub);orders.forEach(o=>o.items=orderItems(o.id));return json(res,200,{orders});}
  if(pathname==='/api/orders'&&method==='POST'){
    const p=auth(req,res,true);
    const items=Array.isArray(body.items)?body.items:[];
    if(!items.length)return error(res,400,'Cart is empty');
    const normalized=items.map(x=>({id:Number(x.id),variantId:Number(x.variantId)||0,quantity:Math.max(1,Math.floor(Number(x.quantity)||1))}));
    const resolved=[];
    for(const x of normalized){
      const product=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(x.id);
      if(!product)return error(res,400,'One or more products are unavailable');
      let unitPrice=product.price, stock=product.stock, variant=null;
      if(x.variantId){ variant=db.prepare('SELECT * FROM product_variants WHERE id=? AND product_id=? AND active=1').get(x.variantId,x.id); if(!variant)return error(res,400,'Selected product variant is unavailable'); unitPrice=variant.price; stock=variant.stock; }
      if(stock<x.quantity)return error(res,409,`Not enough stock for ${product.name}`);
      resolved.push({x,product,variant,unitPrice});
    }
    const subtotal=resolved.reduce((sum,r)=>sum+r.unitPrice*r.x.quantity,0);
    const promoCode=String(body.promoCode||'').trim().toUpperCase();
    let promo=0,promoRecord=null;
    if(promoCode){ promoRecord=promoRow(promoCode); promo=calculatePromo(promoRecord,subtotal); if(!promoRecord||promo<=0)return error(res,400,'Promo code is invalid, expired, or unavailable'); }
    const fee=body.delivery==='express'?10:body.delivery==='pickup'?0:5;
    const total=Math.max(0,subtotal-promo+fee);
    const id=uid('NX'),now=iso();
    db.exec('BEGIN');
    try{
      db.prepare('INSERT INTO orders(id,user_id,customer_name,email,phone,city,address,delivery,payment,note,subtotal,discount,delivery_fee,total,status,progress,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,p?.sub||null,String(body.name||'Guest'),String(body.email||p?.email||''),String(body.phone||''),String(body.city||''),String(body.address||''),String(body.delivery||'standard'),String(body.payment||'cash'),String(body.note||''),subtotal,promo,fee,total,'მიღებულია',25,now,now);
      const ins=db.prepare('INSERT INTO order_items(order_id,product_id,product_name,quantity,price) VALUES(?,?,?,?,?)');
      const decVariant=db.prepare('UPDATE product_variants SET stock=stock-?,updated_at=? WHERE id=?');
      const decProduct=db.prepare('UPDATE products SET stock=stock-?,updated_at=? WHERE id=?');
      resolved.forEach(r=>{ins.run(id,r.product.id,r.product.name,r.x.quantity,r.unitPrice); if(r.variant)decVariant.run(r.x.quantity,now,r.variant.id); else decProduct.run(r.x.quantity,now,r.product.id);});
      if(p)touchUserNotification(p.sub,'შეკვეთა შეიქმნა',`Order #${id} წარმატებით დადასტურდა.`);
      if(promoRecord)db.prepare('UPDATE promo_codes SET uses_count=uses_count+1,updated_at=? WHERE id=?').run(now,promoRecord.id);
      db.exec('COMMIT');
    }catch(e){db.exec('ROLLBACK');return error(res,500,'Could not create order');}
    const order={id,name:String(body.name||'Guest'),email:String(body.email||p?.email||''),phone:String(body.phone||''),city:String(body.city||''),address:String(body.address||''),delivery:String(body.delivery||'standard'),payment:String(body.payment||'cash'),note:String(body.note||''),subtotal,discount:promo,deliveryFee:fee,total,status:'მიღებულია',progress:25,date:now,items:orderItems(id)};
    return json(res,201,{order,orderId:id});
  }

  if(pathname==='/api/promos/validate'&&method==='POST'){const subtotal=Math.max(0,safeNum(body.subtotal));const code=String(body.code||'').trim().toUpperCase();if(!code)return error(res,400,'Promo code is required');const row=promoRow(code);const discount=calculatePromo(row,subtotal);if(!row||discount<=0)return error(res,400,'Promo code is invalid, expired, or unavailable');return json(res,200,{code:row.code,type:row.type,value:row.value,discount,expiresAt:row.expiresAt||''});}
  if(pathname==='/api/tickets'&&method==='GET'){const p=auth(req,res);if(!p)return;const ts=db.prepare('SELECT id,customer_name AS customerName,customer_email AS customerEmail,subject,status,priority,created_at AS date,updated_at AS updatedAt FROM tickets WHERE user_id=? ORDER BY created_at DESC').all(p.sub);ts.forEach(t=>t.replies=db.prepare('SELECT sender_role AS role,sender_name AS name,message AS text,created_at AS date FROM ticket_messages WHERE ticket_id=? ORDER BY id').all(t.id));return json(res,200,{tickets:ts});}
  if(pathname==='/api/tickets'&&method==='POST'){const p=auth(req,res);if(!p)return;const subject=String(body.subject||'').trim(),message=String(body.message||'').trim();if(!subject||!message)return error(res,400,'Subject and message are required');const u=db.prepare('SELECT * FROM users WHERE id=?').get(p.sub),id=uid('TK'),now=iso();db.exec('BEGIN');try{db.prepare("INSERT INTO tickets(id,user_id,customer_name,customer_email,subject,status,priority,created_at,updated_at) VALUES (?,?,?,?,?,'Open','Normal',?,?)").run(id,u.id,u.name,u.email,subject,now,now);db.prepare('INSERT INTO ticket_messages(ticket_id,sender_role,sender_name,message,created_at) VALUES(?,?,?,?,?)').run(id,'customer',u.name,message,now);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');return error(res,500,'Could not create ticket');}return json(res,201,{ticket:{id,customerName:u.name,customerEmail:u.email,subject,status:'Open',priority:'Normal',date:now,replies:[{role:'customer',name:u.name,text:message,date:now}]}});}
  const ticketMsg=pathname.match(/^\/api\/tickets\/([^/]+)\/messages$/);if(ticketMsg&&method==='POST'){const p=auth(req,res);if(!p)return;const t=db.prepare('SELECT * FROM tickets WHERE id=?').get(ticketMsg[1]);if(!t)return error(res,404,'Ticket not found');if(t.user_id!==p.sub)return error(res,403,'Not your ticket');const message=String(body.message||'').trim();if(!message)return error(res,400,'Message is required');db.prepare('INSERT INTO ticket_messages(ticket_id,sender_role,sender_name,message,created_at) VALUES(?,?,?,?,?)').run(t.id,'customer',p.name,message,iso());db.prepare("UPDATE tickets SET status='Open',updated_at=? WHERE id=?").run(iso(),t.id);return json(res,201,{ok:true});}
  if(pathname==='/api/notifications'&&method==='GET'){const p=auth(req,res);if(!p)return;return json(res,200,{notifications:db.prepare('SELECT id,title,body,read,created_at AS time FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 50').all(p.sub)});}
  const adminP=pathname.startsWith('/api/admin/')?requireAdmin(req,res):null;if(pathname.startsWith('/api/admin/')&&!adminP)return;
  if(pathname==='/api/admin/overview'&&method==='GET'){const revenue=db.prepare("SELECT COALESCE(SUM(total),0) v FROM orders WHERE status<>'Cancelled'").get().v;const orders=db.prepare('SELECT COUNT(*) c FROM orders').get().c;const customers=db.prepare("SELECT COUNT(*) c FROM users WHERE role='customer'").get().c;const tickets=db.prepare("SELECT COUNT(*) c FROM tickets WHERE status<>'Closed'").get().c;const lowStock=db.prepare('SELECT COUNT(*) c FROM products WHERE active=1 AND stock<=5').get().c;const pendingOrders=db.prepare("SELECT COUNT(*) c FROM orders WHERE status IN ('მიღებულია','მუშავდება','იგზავნება')").get().c;const recent=db.prepare('SELECT id,total,status,created_at AS date,customer_name AS name FROM orders ORDER BY created_at DESC LIMIT 8').all();return json(res,200,{revenue,orders,customers,tickets,lowStock,pendingOrders,recent});}
  if(pathname==='/api/admin/orders'&&method==='GET'){const orders=db.prepare('SELECT id,customer_name AS name,email,phone,total,status,progress,created_at AS date,updated_at AS updatedAt,delivery,payment FROM orders ORDER BY created_at DESC').all();orders.forEach(o=>o.items=orderItems(o.id));return json(res,200,{orders});}
  const ao=pathname.match(/^\/api\/admin\/orders\/([^/]+)$/);if(ao&&method==='PATCH'){const allowed=['მიღებულია','მუშავდება','იგზავნება','ჩაბარდა','Cancelled'];const st=String(body.status||'');if(!allowed.includes(st))return error(res,400,'Invalid status');const progress=st==='ჩაბარდა'?100:st==='იგზავნება'?75:st==='მუშავდება'?45:st==='Cancelled'?0:25;db.prepare('UPDATE orders SET status=?,progress=?,updated_at=? WHERE id=?').run(st,progress,iso(),ao[1]);const o=db.prepare('SELECT user_id FROM orders WHERE id=?').get(ao[1]);if(o?.user_id)db.prepare('INSERT INTO notifications(user_id,title,body,created_at) VALUES(?,?,?,?)').run(o.user_id,'შეკვეთის სტატუსი შეიცვალა',`Order #${ao[1]} → ${st}`,iso());return json(res,200,{ok:true});}
  if(pathname==='/api/admin/products'&&method==='GET')return json(res,200,{products:publicProducts(false)});
  if(pathname==='/api/admin/upload'&&method==='POST'){const data=String(body.data||'');const m=data.match(/^data:(image\/(?:png|jpeg|jpg|webp|gif));base64,(.+)$/);if(!m)return error(res,400,'Only PNG, JPG, WEBP or GIF images are supported');const buf=Buffer.from(m[2],'base64');if(buf.length>8*1024*1024)return error(res,413,'Image must be 8MB or smaller');const ext=m[1].includes('jpeg')||m[1].includes('jpg')?'jpg':m[1].split('/')[1];const name='product-'+Date.now()+'-'+crypto.randomBytes(5).toString('hex')+'.'+ext;fs.writeFileSync(path.join(UPLOADS,name),buf);return json(res,201,{url:'/uploads/'+name});}
  if(pathname==='/api/admin/products'&&method==='POST'){
    const id=Number(body.id)||Number(db.prepare('SELECT COALESCE(MAX(id),0)+1 id FROM products').get().id),now=iso();
    try{db.prepare('INSERT INTO products(id,name,brand,category,price,old_price,storage,color,badge,description,stock,image,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,String(body.name||'New Product'),String(body.brand||'NEXORA'),String(body.category||'accessories'),safeNum(body.price),safeNum(body.oldPrice),String(body.storage||''),String(body.color||''),String(body.badge||''),String(body.description||''),Math.max(0,Math.floor(safeNum(body.stock))),String(body.image||''),1,now,now);return json(res,201,{product:db.prepare('SELECT id,name,brand,category,price,old_price AS oldPrice,storage,color,badge,description,stock,rating,review_count AS reviewCount,image,active FROM products WHERE id=?').get(id)});}catch(e){return error(res,400,e.message);}
  }
  const ap=pathname.match(/^\/api\/admin\/products\/(\d+)$/);
  if(ap&&method==='GET'){const p=db.prepare('SELECT id,name,brand,category,price,old_price AS oldPrice,storage,color,badge,description,stock,rating,review_count AS reviewCount,image,active FROM products WHERE id=?').get(Number(ap[1]));if(!p)return error(res,404,'Product not found');p.variants=productVariants(p.id,false);return json(res,200,{product:p});}
  if(ap&&method==='PUT'){const id=Number(ap[1]),now=iso(),current=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!current)return error(res,404,'Product not found');const image=body.image!==undefined?String(body.image||''):String(current.image||'');db.prepare('UPDATE products SET name=?,brand=?,category=?,price=?,old_price=?,storage=?,color=?,badge=?,description=?,stock=?,image=?,active=?,updated_at=? WHERE id=?').run(String(body.name??current.name),String(body.brand??current.brand),String(body.category??current.category),safeNum(body.price??current.price),safeNum(body.oldPrice??current.old_price),String(body.storage??current.storage??''),String(body.color??current.color??''),String(body.badge??current.badge??''),String(body.description??current.description??''),Math.max(0,Math.floor(safeNum(body.stock??current.stock))),image,body.active===false?0:1,now,id);return json(res,200,{product:db.prepare('SELECT * FROM products WHERE id=?').get(id)});}
  if(ap&&method==='DELETE'){const id=Number(ap[1]);const r=db.prepare('UPDATE products SET active=0,updated_at=? WHERE id=?').run(iso(),id);if(!r.changes)return error(res,404,'Product not found');return json(res,200,{ok:true});}
  const restore=pathname.match(/^\/api\/admin\/products\/(\d+)\/restore$/);if(restore&&method==='POST'){const r=db.prepare('UPDATE products SET active=1,updated_at=? WHERE id=?').run(iso(),Number(restore[1]));if(!r.changes)return error(res,404,'Product not found');return json(res,200,{ok:true});}
  const vr=pathname.match(/^\/api\/admin\/products\/(\d+)\/variants$/);
  if(vr&&method==='POST'){const pid=Number(vr[1]);if(!db.prepare('SELECT id FROM products WHERE id=?').get(pid))return error(res,404,'Product not found');const now=iso();const info=db.prepare('INSERT INTO product_variants(product_id,name,sku,price,old_price,stock,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(pid,String(body.name||'Variant'),String(body.sku||''),safeNum(body.price),safeNum(body.oldPrice),Math.max(0,Math.floor(safeNum(body.stock))),1,now,now);return json(res,201,{variant:db.prepare('SELECT id,product_id AS productId,name,sku,price,old_price AS oldPrice,stock,active FROM product_variants WHERE id=?').get(info.lastInsertRowid)});}
  const avi=pathname.match(/^\/api\/admin\/variants\/(\d+)$/);if(avi&&method==='PUT'){const id=Number(avi[1]),cur=db.prepare('SELECT * FROM product_variants WHERE id=?').get(id);if(!cur)return error(res,404,'Variant not found');db.prepare('UPDATE product_variants SET name=?,sku=?,price=?,old_price=?,stock=?,active=?,updated_at=? WHERE id=?').run(String(body.name??cur.name),String(body.sku??cur.sku),safeNum(body.price??cur.price),safeNum(body.oldPrice??cur.old_price),Math.max(0,Math.floor(safeNum(body.stock??cur.stock))),body.active===false?0:1,iso(),id);return json(res,200,{ok:true});}
  if(avi&&method==='DELETE'){const r=db.prepare('UPDATE product_variants SET active=0,updated_at=? WHERE id=?').run(iso(),Number(avi[1]));if(!r.changes)return error(res,404,'Variant not found');return json(res,200,{ok:true});}
  if(avi&&method==='POST'){const r=db.prepare('UPDATE product_variants SET active=1,updated_at=? WHERE id=?').run(iso(),Number(avi[1]));if(!r.changes)return error(res,404,'Variant not found');return json(res,200,{ok:true});}
  if(pathname==='/api/admin/reviews'&&method==='GET'){const reviews=db.prepare("SELECT r.id,r.product_id AS productId,p.name AS productName,r.rating,r.text,r.created_at AS date,u.name AS customerName,u.email AS customerEmail FROM reviews r LEFT JOIN products p ON p.id=r.product_id LEFT JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC").all();return json(res,200,{reviews});}
  const ar=pathname.match(/^\/api\/admin\/reviews\/(\d+)$/);if(ar&&method==='DELETE'){const row=db.prepare('SELECT product_id FROM reviews WHERE id=?').get(Number(ar[1]));if(!row)return error(res,404,'Review not found');db.prepare('DELETE FROM reviews WHERE id=?').run(Number(ar[1]));const agg=db.prepare('SELECT ROUND(COALESCE(AVG(rating),4.8),1) AS avg,COUNT(*) AS count FROM reviews WHERE product_id=?').get(row.product_id);db.prepare('UPDATE products SET rating=?,review_count=?,updated_at=? WHERE id=?').run(Number(agg.avg),Number(agg.count),iso(),row.product_id);return json(res,200,{ok:true});}
  if(pathname==='/api/admin/promos'&&method==='GET')return json(res,200,{promos:db.prepare('SELECT id,code,type,value,max_uses AS maxUses,uses_count AS usesCount,expires_at AS expiresAt,active,created_at AS createdAt FROM promo_codes ORDER BY id DESC').all()});
  if(pathname==='/api/admin/promos'&&method==='POST'){const code=String(body.code||'').trim().toUpperCase();if(!/^[A-Z0-9_-]{3,32}$/.test(code))return error(res,400,'Invalid promo code');if(!['percent','fixed'].includes(body.type))return error(res,400,'Invalid promo type');const value=safeNum(body.value);if(value<=0)return error(res,400,'Value must be greater than 0');const now=iso();try{const info=db.prepare('INSERT INTO promo_codes(code,type,value,max_uses,uses_count,expires_at,active,created_at,updated_at) VALUES(?,?,?,?,0,?,1,?,?)').run(code,body.type,value,Math.max(0,Math.floor(safeNum(body.maxUses))),String(body.expiresAt||''),now,now);return json(res,201,{id:info.lastInsertRowid});}catch(e){return error(res,409,'Promo code already exists');}}
  const promoMatch=pathname.match(/^\/api\/admin\/promos\/(\d+)$/);if(promoMatch&&method==='PUT'){const id=Number(promoMatch[1]),cur=db.prepare('SELECT * FROM promo_codes WHERE id=?').get(id);if(!cur)return error(res,404,'Promo not found');db.prepare('UPDATE promo_codes SET code=?,type=?,value=?,max_uses=?,expires_at=?,active=?,updated_at=? WHERE id=?').run(String(body.code??cur.code).toUpperCase(),String(body.type??cur.type),safeNum(body.value??cur.value),Math.max(0,Math.floor(safeNum(body.maxUses??cur.max_uses))),String(body.expiresAt??cur.expires_at??''),body.active===false?0:1,iso(),id);return json(res,200,{ok:true});}
  if(promoMatch&&method==='DELETE'){const r=db.prepare('UPDATE promo_codes SET active=0,updated_at=? WHERE id=?').run(iso(),Number(promoMatch[1]));if(!r.changes)return error(res,404,'Promo not found');return json(res,200,{ok:true});}
  if(pathname==='/api/admin/users'&&method==='GET'){const users=db.prepare("SELECT u.id,u.name,u.email,u.phone,u.created_at AS createdAt,COUNT(DISTINCT o.id) orders,COALESCE(SUM(o.total),0) spent,COUNT(DISTINCT t.id) tickets FROM users u LEFT JOIN orders o ON o.user_id=u.id LEFT JOIN tickets t ON t.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC").all();return json(res,200,{users});}
  if(pathname==='/api/admin/tickets'&&method==='GET'){const tickets=db.prepare("SELECT id,user_id AS userId,customer_name AS customerName,customer_email AS customerEmail,subject,status,priority,created_at AS date,updated_at AS updatedAt FROM tickets ORDER BY CASE status WHEN 'Open' THEN 0 WHEN 'Pending' THEN 1 ELSE 2 END,updated_at DESC").all();tickets.forEach(t=>t.replies=db.prepare('SELECT sender_role AS role,sender_name AS name,message AS text,created_at AS date FROM ticket_messages WHERE ticket_id=? ORDER BY id').all(t.id));return json(res,200,{tickets});}
  const at=pathname.match(/^\/api\/admin\/tickets\/([^/]+)$/);if(at&&method==='PATCH'){if(!['Open','Pending','Closed'].includes(String(body.status||'')))return error(res,400,'Invalid status');db.prepare('UPDATE tickets SET status=?,priority=?,updated_at=? WHERE id=?').run(String(body.status),String(body.priority||'Normal'),iso(),at[1]);return json(res,200,{ok:true});}
  const atm=pathname.match(/^\/api\/admin\/tickets\/([^/]+)\/messages$/);if(atm&&method==='POST'){const t=db.prepare('SELECT * FROM tickets WHERE id=?').get(atm[1]);if(!t)return error(res,404,'Ticket not found');const message=String(body.message||'').trim();if(!message)return error(res,400,'Message is required');const now=iso();db.prepare('INSERT INTO ticket_messages(ticket_id,sender_role,sender_name,message,created_at) VALUES(?,?,?,?,?)').run(t.id,'admin','NEXORA Support',message,now);db.prepare("UPDATE tickets SET status='Pending',updated_at=? WHERE id=?").run(now,t.id);if(t.user_id)db.prepare('INSERT INTO notifications(user_id,title,body,created_at) VALUES(?,?,?,?)').run(t.user_id,'Support-ის პასუხი მივიღეთ',`Ticket #${t.id}: ${message}`,now);return json(res,201,{ok:true});}
  if(pathname==='/api/admin/notifications'&&method==='GET')return json(res,200,{notifications:db.prepare('SELECT id,title,body,read,created_at AS time FROM notifications WHERE user_id IS NULL ORDER BY id DESC LIMIT 100').all()});
  if(pathname==='/api/admin/notifications'&&method==='POST'){const title=String(body.title||'').trim(),msg=String(body.body||'').trim();if(!title||!msg)return error(res,400,'Title and body are required');const now=iso();const users=db.prepare("SELECT id FROM users WHERE role='customer'").all();db.exec('BEGIN');try{db.prepare('INSERT INTO notifications(user_id,title,body,created_at) VALUES(NULL,?,?,?)').run(title,msg,now);for(const u of users)db.prepare('INSERT INTO notifications(user_id,title,body,created_at) VALUES(?,?,?,?)').run(u.id,title,msg,now);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');return error(res,500,'Could not send notification');}return json(res,201,{ok:true,sent:users.length});}
  if(pathname==='/api/admin/settings'&&method==='GET'){const rows=db.prepare('SELECT key,value FROM settings').all();return json(res,200,{settings:Object.fromEntries(rows.map(r=>[r.key,r.value]))});}
  if(pathname==='/api/admin/settings'&&method==='PUT'){const entries=Object.entries(body||{});db.exec('BEGIN');try{for(const [k,v] of entries)db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');return error(res,500,'Could not save settings');}return json(res,200,{ok:true});}
  return error(res,404,'API route not found');
}

const server=http.createServer(async (req,res)=>{
  try{
    const url=new URL(req.url,'http://localhost');
    if(url.pathname==='/health'&&req.method==='GET') return json(res,200,{ok:true,service:'NEXORA',time:iso()});
    if(url.pathname.startsWith('/api/')) return await api(req,res,url);
    if(url.pathname==='/admin'||url.pathname==='/admin.html') return fileResponse(req,res,'/admin.html');
    return fileResponse(req,res,url.pathname);
  }catch(e){console.error(e);return error(res,500,'Internal server error');}
});
server.listen(PORT,()=>console.log(`NEXORA running at http://localhost:${PORT}`));
